spring:
  datasource:
    url: jdbc:sqlite:back/birdme.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大大小
      max-request-size: 10MB  # 单次请求最大总大小
      enabled: true            # 启用文件上传

mybatis-plus:
  typeAliasesPackage: com.java.birdme.bean
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

uploadPath: d:/uploads/birdme
